apiVersion: v1
kind: Namespace
metadata:
  name: ml-autoscaler
  labels:
    name: ml-autoscaler
    purpose: application
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    purpose: observability
