apiVersion: v1
kind: Service
metadata:
  name: forecaster
  namespace: ml-autoscaler
spec:
  selector:
    app: forecaster
  ports:
    - name: http
      port: 8001
      targetPort: 8001
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forecaster
  namespace: ml-autoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forecaster
  template:
    metadata:
      labels:
        app: forecaster
    spec:
      containers:
      - name: forecaster
        image: forecaster:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8001
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: PROMETHEUS_URL
          value: "http://prometheus.monitoring.svc.cluster.local:9090"
        - name: FORECAST_HORIZON_MINUTES
          value: "10"
        - name: HISTORY_HOURS
          value: "24"
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
          requests:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 5
